In [1]:
import pandas as pd
pd.options.display.max_columns=30

In [2]:
kc_df = pd.read_csv('../data/kc_house_data.csv')
kc_df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

### Bathroom fractions explained

0.25 → toilet only

0.5 → toilet + sink (half bath)

0.75 → toilet + sink + shower (no bathtub)

1.0 → full bathroom (toilet + sink + shower/bathtub)

In [3]:
kc_df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
#transformations:
kc_df['date'] = pd.to_datetime(kc_df['date'], format='%Y%m%dT%H%M%S').dt.strftime('%Y-%m-%d')

In [5]:
from datetime import datetime

s = "20141209T000000"
dt = datetime.strptime(s, "%Y%m%dT%H%M%S")
formatted = dt.strftime("%Y-%m-%d")

print(formatted)

2014-12-09

In [6]:
kc_df.shape

(21613, 21)

In [7]:
kc_df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

## Demographic data

In [8]:
demo_data = pd.read_csv("../data/zipcode_demographics.csv")

In [9]:
demo_data

,ppltn_qty,urbn_ppltn_qty,sbrbn_ppltn_qty,farm_ppltn_qty,non_farm_qty,medn_hshld_incm_amt,medn_incm_per_prsn_amt,hous_val_amt,edctn_less_than_9_qty,edctn_9_12_qty,edctn_high_schl_qty,edctn_some_clg_qty,edctn_assoc_dgre_qty,edctn_bchlr_dgre_qty,edctn_prfsnl_qty,per_urbn,per_sbrbn,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl,zipcode
0,38249.0,37394.0,0.0,0.0,855.0,66051.0,25219.0,192000.0,437.0,2301.0,7135.0,7787.0,2202.0,4964.0,1783.0,97.0,0.0,0.0,2.0,1.0,6.0,18.0,20.0,5.0,12.0,4.0,98042
1,22036.0,22036.0,0.0,0.0,0.0,91904.0,53799.0,573900.0,149.0,404.0,1441.0,2826.0,673.0,5961.0,4878.0,100.0,0.0,0.0,0.0,0.0,1.0,6.0,12.0,3.0,27.0,22.0,98040
2,18194.0,18194.0,0.0,0.0,0.0,61813.0,31765.0,246600.0,269.0,905.0,2386.0,3703.0,1211.0,3547.0,1762.0,100.0,0.0,0.0,0.0,1.0,4.0,13.0,20.0,6.0,19.0,9.0,98028
3,21956.0,21956.0,0.0,0.0,0.0,47461.0,22158.0,175400.0,925.0,1773.0,4530.0,4630.0,1277.0,2688.0,952.0,100.0,0.0,0.0,0.0,4.0,8.0,20.0,21.0,5.0,12.0,4.0,98178
4,22814.0,22814.0,0.0,0.0,0.0,48606.0,28398.0,252600.0,599.0,1148.0,3077.0,4085.0,1326.0,5341.0,2818.0,100.0,0.0,0.0,0.0,2.0,5.0,13.0,17.0,5.0,23.0,12.0,98007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,35140.0,35021.0,0.0,0.0,119.0,81929.0,41856.0,335900.0,212.0,865.0,3061.0,5361.0,1616.0,9604.0,5453.0,99.0,0.0,0.0,0.0,0.0,2.0,8.0,15.0,4.0,27.0,15.0,98006
66,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,3755.5,4638.0,1417.5,4822.0,2072.0,100.0,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98074
67,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,3755.5,4638.0,1417.5,4822.0,2072.0,100.0,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98077
68,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,3755.5,4638.0,1417.5,4822.0,2072.0,100.0,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98030
69,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,3755.5,4638.0,1417.5,4822.0,2072.0,100.0,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98075

In [10]:
demo_data.dtypes

ppltn_qty                 float64
urbn_ppltn_qty            float64
sbrbn_ppltn_qty           float64
farm_ppltn_qty            float64
non_farm_qty              float64
medn_hshld_incm_amt       float64
medn_incm_per_prsn_amt    float64
hous_val_amt              float64
edctn_less_than_9_qty     float64
edctn_9_12_qty            float64
edctn_high_schl_qty       float64
edctn_some_clg_qty        float64
edctn_assoc_dgre_qty      float64
edctn_bchlr_dgre_qty      float64
edctn_prfsnl_qty          float64
per_urbn                  float64
per_sbrbn                 float64
per_farm                  float64
per_non_farm              float64
per_less_than_9           float64
per_9_to_12               float64
per_hsd                   float64
per_some_clg              float64
per_assoc                 float64
per_bchlr                 float64
per_prfsnl                float64
zipcode                     int64
dtype: object

In [11]:
demo_data.isna().sum()

ppltn_qty                 0
urbn_ppltn_qty            0
sbrbn_ppltn_qty           0
farm_ppltn_qty            0
non_farm_qty              0
medn_hshld_incm_amt       0
medn_incm_per_prsn_amt    0
hous_val_amt              0
edctn_less_than_9_qty     0
edctn_9_12_qty            0
edctn_high_schl_qty       0
edctn_some_clg_qty        0
edctn_assoc_dgre_qty      0
edctn_bchlr_dgre_qty      0
edctn_prfsnl_qty          0
per_urbn                  0
per_sbrbn                 0
per_farm                  0
per_non_farm              0
per_less_than_9           0
per_9_to_12               0
per_hsd                   0
per_some_clg              0
per_assoc                 0
per_bchlr                 0
per_prfsnl                0
zipcode                   0
dtype: int64

In [12]:
demo_data.describe()

,ppltn_qty,urbn_ppltn_qty,sbrbn_ppltn_qty,farm_ppltn_qty,non_farm_qty,medn_hshld_incm_amt,medn_incm_per_prsn_amt,hous_val_amt,edctn_less_than_9_qty,edctn_9_12_qty,edctn_high_schl_qty,edctn_some_clg_qty,edctn_assoc_dgre_qty,edctn_bchlr_dgre_qty,edctn_prfsnl_qty,per_urbn,per_sbrbn,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl,zipcode
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,25655.242857,24543.814286,192.457143,16.442857,866.614286,57530.785714,30623.342857,263954.285714,633.614286,1472.514286,3907.714286,4986.071429,1476.228571,4985.357143,2358.300000,90.485714,2.028571,0.100000,7.014286,1.885714,5.228571,14.642857,18.814286,5.085714,19.142857,8.771429,98077.300000
std,11550.597239,12613.622494,1359.783707,59.566948,2007.028175,16166.136140,10256.973419,107660.168762,653.259925,989.467354,2232.555562,2482.385858,728.813820,2897.640099,1729.814578,25.153294,12.034939,0.386362,19.557787,2.183886,2.687445,4.839558,3.084758,0.880429,7.589630,5.420496,56.622408
min,3037.000000,0.000000,0.000000,0.000000,0.000000,32085.000000,17087.000000,141500.000000,4.000000,51.000000,160.000000,359.000000,71.000000,427.000000,186.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5.000000,11.000000,2.000000,6.000000,2.000000,98001.000000
25%,19449.500000,18943.500000,0.000000,0.000000,0.000000,46397.750000,24422.000000,193225.000000,200.000000,707.750000,2215.000000,3747.500000,1063.000000,2769.500000,1033.750000,98.250000,0.000000,0.000000,0.000000,1.000000,3.000000,11.000000,17.250000,5.000000,12.250000,4.000000,98029.250000
50%,23926.500000,23298.000000,0.000000,0.000000,0.000000,56933.000000,27639.500000,239850.000000,406.000000,1213.000000,3755.500000,4638.000000,1417.500000,4822.000000,2072.000000,100.000000,0.000000,0.000000,0.000000,1.000000,5.000000,15.000000,19.000000,5.000000,19.000000,7.500000,98067.500000
75%,31013.750000,30773.500000,0.000000,0.000000,313.000000,63599.500000,35207.250000,288925.000000,899.750000,1933.750000,5268.750000,6055.000000,1736.500000,6527.250000,3312.000000,100.000000,0.000000,0.000000,0.750000,2.000000,7.000000,18.000000,20.000000,6.000000,25.000000,12.000000,98117.750000
max,64181.000000,64181.000000,11176.000000,439.000000,9973.000000,132665.000000,81926.000000,790300.000000,3671.000000,4483.000000,12241.000000,13680.000000,3998.000000,14271.000000,8891.000000,100.000000,81.000000,2.000000,98.000000,11.000000,11.000000,25.000000,34.000000,7.000000,39.000000,24.000000,98199.000000

In [13]:
future=pd.read_csv('../data/future_unseen_examples.csv')

In [14]:
future.shape

(100, 18)

In [15]:
future.isna().sum()

bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [2]:
import requests
df = pd.read_csv('../data/future_unseen_examples.csv')
test_cases = df.head(5).copy()
test_cases['zipcode'] = 0

In [7]:

# Test each case
for idx, row in test_cases.iterrows():
    print(row)
    response = requests.post(
        'http://localhost:8080/predict',
        json=row.to_dict()
    )
    print(f"Row {idx}: {response.status_code}")
    print(response.json())
    break

bedrooms            4.0000
bathrooms           1.0000
sqft_living      1680.0000
sqft_lot         5043.0000
floors              1.5000
waterfront          0.0000
view                0.0000
condition           4.0000
grade               6.0000
sqft_above       1680.0000
sqft_basement       0.0000
yr_built         1911.0000
yr_renovated        0.0000
zipcode             0.0000
lat                47.5354
long             -122.2730
sqft_living15    1560.0000
sqft_lot15       5765.0000
Name: 0, dtype: float64
Row 0: 400
{'error': "Missing features to predictions, columns missing ['ppltn_qty', 'urbn_ppltn_qty', 'sbrbn_ppltn_qty', 'farm_ppltn_qty', 'non_farm_qty', 'medn_hshld_incm_amt', 'medn_incm_per_prsn_amt', 'hous_val_amt', 'edctn_less_than_9_qty', 'edctn_9_12_qty', 'edctn_high_schl_qty', 'edctn_some_clg_qty', 'edctn_assoc_dgre_qty', 'edctn_bchlr_dgre_qty', 'edctn_prfsnl_qty', 'per_urbn', 'per_sbrbn', 'per_farm', 'per_non_farm', 'per_less_than_9', 'per_9_to_12', 'per_hsd', 'per_some_clg', 'per_assoc', 'per_bchlr', 'per_prfsnl']"}

## correlational data